### ISSUE TITLE
update_server.bat - incorrect command order.

### ISSUE THREAD

**Issue by CTOUT** [darryl-h/v-rising-server#1] opened 2022-06-18 08:35 UTC
The version of the update_server.bat currently being produced appears to be incorrect.
It runs steamcmd before warning anyone that the server is going to be restarted.  It then fails to announce anything because steamcmd has already stopped the process.

I suggest the order becomes as below: -

```
@echo off
mcrcon.exe -H 127.0.0.1 -P 25575 -p PASSWORD "announcerestart 10"
timeout 600
nssm.exe stop VRisingServer
steamcmd.exe +login anonymous +app_update 1829350 validate +quit
nssm.exe start VRisingServer
```

**Comment by CTOUT** [comment] 2022-06-18 08:37
As part of the script that would be: - 
```
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "@echo off"
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "$InstallPath\mcrcon.exe -H 127.0.0.1 -P 25575 -p $RCONPassword 'announcerestart 10'"
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "timeout 600"
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "$InstallPath\nssm.exe stop VRisingServer-$GamePort"
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "$InstallPath\steamcmd.exe +login anonymous +app_update 1829350 validate +quit"
Add-Content -Path "$InstallPath\steamapps\common\VRisingDedicatedServer\update_server.bat" -Value "$InstallPath\nssm.exe start VRisingServer-$GamePort"
```

**Comment by darryl-h** [comment] 2022-06-24 20:38
Thanks for the feedback! 

I used to have the service off while I did the update as well, but it seems that you can update the files on disk, and it will happily run from memory until you restart the server at which time the actual changes will take place. 

Using the method I prescribe, have you encountered any errors? If so, I will happily change it back, if not, then this reduces the downtime of the server.

Again, thank you VERY much for reporting! Please let me know, I haven't seen any problems myself, but very open to suggestions!

**Comment by CTOUT** [comment] 2022-06-25 06:53
Hi Darryl,

I thought I had noticed the service stop once - but that may depend on whether anything is updated vs just being verified.  When I try it knowing there are no updates available, there is no service impact.
However, knowing the memory leaks this game has suffered in the past, a daily restart isn't necessarily bad! 😸

**Comment by darryl-h** [comment] 2022-06-25 19:03
Thanks Chris!

Your not wrong with the memory issues there, but please let me know if you experience any issue with doing the update first, then the restart after. 

If you do experience issues, then I'll look at moving it back to the way it was, which was:

- Notify Users
- Stop Service
- Update Server
- Start Service

Rather than what it is now which is:
- Update Server
- Notify Users
- Restart Service

If I do need to do the update while the service is down, I'll (ideally) need figure out how to give the server enough time to update, rather than arbitrarily giving it some time interval and hoping it completes in that time.

Thank you again for the report, I'm going to close this one as 'by design' but please re-open if you observe bugs, or if I've not addressed your concern!

**Closed as completed by darryl-h** 2022-06-25 19:03 UTC
Labels: wontfix
